version: '3.8'
services:
  # frontend: 
  #   build: news-trading-frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  backend:
    build: news-trading-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  scraper:
    build: ./scraper
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
